// ============================================================================
// THE RIG CONTRACT, NAMED
//
// The crew GLBs are generated by scripts/build_crew.py, which authors the rower
// as Rower -> Rower_Torso / Rower_LeftArm / Rower_RightArm / ... and the oars as
// LeftOar / RightOar. The scene animates those nodes by name.
//
// Naming them here rather than inline means a model regenerated with different
// names fails a test, instead of silently freezing the rower mid-stroke — which
// is exactly how the oars came to sweep while the rower sat rigid (#273).
// ============================================================================

/** Rower nodes the scene animates through the stroke. */
export const GLB_ROWER_NODES = [
  // The slide. Authored by the rig alongside the oars and never animated: the
  // rower's legs went down and their seat stayed where it was (#330).
  'Seat',
  'Rower_Torso',
  'Rower_LeftArm',
  'Rower_RightArm',
  'LeftArm_Fore',
  'RightArm_Fore',
] as const;

/** Oar nodes the scene sweeps about their gates. */
export const GLB_OAR_NODES = ['LeftOar', 'RightOar'] as const;
